### ISSUE TITLE
cElementTree.ParseError: not well-formed (invalid token): line 1, column 0

### ISSUE THREAD

**Issue by PygmalionChen** [MLDroid/graph2vec_tf#1]
I run the code but get this issue.

**Comment by annamalai-nr** [comment]
Did you try this? https://stackoverflow.com/questions/13046240/parseerror-not-well-formed-invalid-token-using-celementtree

**Comment by PygmalionChen** [comment]
thank you ,got it.

**Comment by khaifahmi99** [comment]
HI, can you explain more on this fix?
