### ISSUE TITLE
Only using first entry on each line?

### ISSUE THREAD

**Issue by bkj** [MLDroid/graph2vec_tf#3]
In `src/make_graph2vec_corpus.py`, you create `center` and `nei_list` and write 

```
sentence = center + ' ' + nei_list
```

to file.  However, in `corpus_parser.py`, you only ever read the first entry on each line.  Can you explain going on there?

Thanks
~ Ben

**Comment by annamalai-nr** [comment]
Yes, you are correct. Graph2vec uses only the center and not the nei_list when (target, context) pairs are generated in 

>corpus_parser.py

More precisely, **target = graph id** and **context = subgraph id** for graph2vec. Actually, 

> src/make_graph2vec_corpus.py

is same for subgraph2vec and graph2vec repositories. Subgraph2vec needs 'nei_list' and graph2vec does not. Hence you may comment the portion of code that computes nei_list and graph2vec code would still work.
